{
    "status":0,
    "message":"success",
    "ids": [1,3,5,7],
    "data": [
        {
            "id":"1",
            "name":"郑州"
        },
        {
            "id":"2",
            "name":"宁波"
        },
        {
            "id":"3",
            "name":"广州"
        },
        {
            "id":"4",
            "name":"深圳"
        },
        {
            "id":"5",
            "name":"上海"
        },
        {
            "id":"6",
            "name":"杭州"
        },
        {
            "id":"7",
            "name":"重庆"
        }
    ]
}