[{
            "id": 1,
            "name": "微盟",
            "parentid": 0,
            "wid": 1,
            "pinyinname": "WeiMeng",
            "is_readonly":true
        }, {
            "id": 2,
            "name": "研发部",
            "parentid": 1,
                "wid": 2,
            "pinyinname": "YanFaBu"
        }, {
            "id": 3,
            "name": "产品部",
            "parentid": 1,
            "wid": 3,
            "pinyinname": "ChanPinBu"
        }, {
            "id": 4,
            "name": "渠道部",
            "parentid": 1,
            "pinyinname": "QuDaoBu"
        }, {
            "id": 5,
            "name": "销售部",
            "parentid": 1,
            "pinyinname": "XiaoShouBu"
        }, {
            "id": 6,
            "name": "客服部",
            "parentid": 1,
            "pinyinname": "KeFuBu"
        }, {
            "id": 17,
            "name": "广研",
            "parentid": 1,
            "pinyinname": "GuangYan"
        }, {
            "id": 21,
            "name": "ceo",
            "parentid": 1,
            "pinyinname": "ceo"
        }, {
            "id": 25,
            "name": "测试信息",
            "parentid": 1,
            "pinyinname": "CeShiXinXi"
        }, {
            "id": 7,
            "name": "产品一部",
            "parentid": 3,
            "pinyinname": "ChanPinYiBu"
        }, {
            "id": 9,
            "name": "产品3部",
            "parentid": 3,
            "pinyinname": "ChanPin3Bu"
        }, {
            "id": 20,
            "name": "运营中心",
            "parentid": 17,
            "pinyinname": "YunYingZhongXin"
        }, {
            "id": 19,
            "name": "企业微信",
            "parentid": 17,
            "pinyinname": "QiYeWeiXin"
        }, {
            "id": 18,
            "name": "产品中心",
            "parentid": 17,
            "pinyinname": "ChanPinZhongXin"
        }, {
            "id": 26,
            "name": "aaaa",
            "parentid": 25,
            "pinyinname": "aaaa"
        }, {
            "id": 28,
            "name": "bbb",
            "parentid": 25,
            "pinyinname": "bbb"
        }, {
            "id": 29,
            "name": "bbbc",
            "parentid": 25,
            "pinyinname": "bbbc"
        }, {
            "id": 8,
            "name": "产品一部一组",
            "parentid": 7,
            "pinyinname": "ChanPinYiBuYiZu"
        }, {
            "id": 10,
            "name": "电商产品组",
            "parentid": 9,
            "pinyinname": "DianShangChanPinZu"
        }, {
            "id": 11,
            "name": "111222",
            "parentid": 8,
            "pinyinname": "111222"
        }, {
            "id": 12,
            "name": "111",
            "parentid": 8,
            "pinyinname": "111"
        }, {
            "id": 24,
            "name": "ddd",
            "parentid": 8,
            "pinyinname": "ddd"
        }, {
            "id": 22,
            "name": "222222222222222",
            "parentid": 10,
            "pinyinname": "222222222222222"
        }, {
            "id": 13,
            "name": "222",
            "parentid": 12,
            "pinyinname": "222"
        }, {
            "id": 16,
            "name": "333",
            "parentid": 12,
            "pinyinname": "333"
        }, {
            "id": 14,
            "name": "2222",
            "parentid": 13,
            "pinyinname": "2222"
        }, {
            "id": 15,
            "name": "111",
            "parentid": 14,
            "pinyinname": "111"
        }, {
            "id": 23,
            "name": "dd",
            "parentid": 15,
            "pinyinname": "dd"
        }]