<?php 
	$s='{
		"status":0,
		"message":"",
		"data":{
			"count":800,
		    "currentPage":1,
		    "totalPage":89,
			"list":[
				{
					"id":"g2222",
					"title":"g2222",
					"date":"09月08日",
					"subtitle":"22",
					"img":"/assets/images/avatar12.jpg"
				},
				{
					"id":"g2223",
					"title":"g2223",
					"date":"09月08日",
					"subtitle":"22",
					"img":"/assets/images/avatar12.jpg",
					"isInValid": "true",
					"item":[
						{
							"title":"22222",
							"img":"/assets/images/scene.jpg"
						}
					]
				},
				{
					"id":"g2224",
					"title":"g2224",
					"date":"09月08日",
					"subtitle":"22",
					"img":"/assets/images/avatar12.jpg",
					"item":[
						{
							"title":"22333",
							"img":"/assets/images/scene.jpg"
						},
						{
							"title":"33333",
							"img":"/assets/images/scene.jpg"
						}
					]
				},
				{
					"id":"g2222",
					"title":"g2222",
					"date":"09月08日",
					"subtitle":"22",
					"img":"/assets/images/avatar12.jpg"
				},
				{
					"id":"g2223",
					"title":"g2223",
					"date":"09月08日",
					"subtitle":"22",
					"img":"/assets/images/avatar12.jpg",
					"isInValid": "true",
					"item":[
						{
							"title":"22222",
							"img":"/assets/images/scene.jpg"
						}
					]
				},
				{
					"id":"g2224",
					"title":"g2224",
					"date":"09月08日",
					"subtitle":"22",
					"img":"/assets/images/avatar12.jpg",
					"item":[
						{
							"title":"22333",
							"img":"/assets/images/scene.jpg"
						},
						{
							"title":"33333",
							"img":"/assets/images/scene.jpg"
						}
					]
				}
			]
		}
	}';


echo $s;
?>